# Welcome to Jekyll!

# Website settings
title: "Hugo Duportet"
description: "Resume"
keywords: ""
baseurl: "/"


# author
author:
  name: 'Hugo Duportet'
  first_name: 'Hugo'
  last_name: 'Duportet'
  email: 'hugo.duportet@.gmail.com'
  facebook_username: ''
  github_username: ''
  avatar: 'static/img/landing/portrait1.png'
  desc: 'I am a data scientist with a strong background in mathematics, with data mining, machine learning and coding experience. \n
  Through academic and profesionnal projects, I gained significant data mining, machine learning and coding experience. \n
  Life is a continuous learning process, so work makes me more rigorous, musics makes my life more colorful.'
#
# # comment
# changyan:
#   # appid: cysfY7ULn
#   # conf: prod_861928934cecb7a18e15bedaed9dae29
# disqus:
#   name: jalpc
#   public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7
#
# # share
# bshare:
#   uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75
#
# # baidu analytics
# ba:
#   # uuid: 317acca9ef9255b934e46371e471431d
#
# # google analytics
# ga:
#   id: UA-73784599-1
#
# # growingIO
# gio:
#   id: a49d4901c7853da9


# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
