# Welcome to Jekyll!

# Website settings
title: "Orhan YAZAR"
description: "Resume"
keywords: ""
url: "https://orhanyaz.github.io"
baseurl: "/OnlineResume/"

# author
author:
  name: 'Orhan YAZAR'
  first_name: 'Orhan'
  last_name: 'YAZAR'
  email: 'yazar.or@gmail.com'
  github_username: 'OrhanYaz'
  avatar: 'static/img/landing/portrait1.png'
  desc: 'I am a junior data scientist with a strong background in mathematics, with data mining, machine learning and coding experience. \n
  Through academic and profesionnal projects, I gained significant data mining, machine learning and coding experience. \n
  Life is a continuous learning process, so work makes me more rigorous, musics makes my life more colorful.'

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
